### ISSUE TITLE
Cannot create HERE SDK object before MapEngine is initialized

### ISSUE THREAD

**Issue by InfraRedApple** [heremaps/here-android-sdk-examples#228]
I have attempted to use the SDK to do GeoCoding in my project. But I get the error:

> Cannot create HERE SDK object before MapEngine is initialized.

So I downloaded, setup with my api keys, filled in the Intent and Service nodes in the manifest,  added the latest HERE-sdk.aar  to the Libs folder and ran  Here's OWN EXAMPLE _[geocoder-and-reverse-geocoder](https://github.com/heremaps/here-android-sdk-examples/tree/master/geocoder-and-reverse-geocoder)_ and the exact same issue happens when attempting to GeoCode.

I am using **HERE SDK Version: 3.11.2.82**, I am running in the emulator using a Pixel 2 with API 28 and API 27.

All permissions were granted.

As soon as the example app starts up, you are presented with two buttons. Upon clicking **_Geocode Request_**, the app crashes. 

```
 --------- beginning of crash
2019-04-05 06:16:54.216 28389-28389/com.here.android.example.geocoding E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.here.android.example.geocoding, PID: 28389
    com.here.android.mpa.common.UnintializedMapEngineException: Cannot create HERE SDK object before MapEngine is initialized. See MapEngine.init()
        at com.nokia.maps.BaseNativeObject.u(BaseNativeObject.java:39)
        at com.nokia.maps.ee.a(PlacesUtils.java:24)
        at com.here.android.mpa.search.Request.a(Request.java:287)
        at com.here.android.mpa.search.GeocodeRequest.execute(GeocodeRequest.java:168)
        at com.here.android.example.geocoding.MainView.triggerGeocodeRequest(MainView.java:124)
        at com.here.android.example.geocoding.MainView.access$100(MainView.java:47)
        at com.here.android.example.geocoding.MainView$2.onClick(MainView.java:101)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-04-05 06:16:54.217 28389-28389/com.here.android.example.geocoding E/HERE-SDK: HERE SDK Version: 3.11.2.82

```

**Comment by starand** [comment]
Hi @InfraRedApple,

You cannot create some SDK objects before engine initialization. You can do that after initialization.
Most likely you got "missing library" error, because we do not include in SDK x86_64 native libraries.

Which ABI is used in your emulator? x86_64?

**Comment by InfraRedApple** [comment]
@starand The emulators are not running x86_64. They are running x86.

**Comment by starand** [comment]
we will try to reproduce.
Anyway, what error code do you get in onEngineInitializationCompleted(Error error) callback?
