### ISSUE TITLE
GeocodeRequest crash on Kotlin

### ISSUE THREAD

**Issue by inglab-guster** [heremaps/here-android-sdk-examples#246]
Android version: Android 9
Language: Kotlin
Exception: Caused by: java.lang.ExceptionInInitializerError

`App Id` and `App Code` are all set in `AndroidManifest`

Details:
```
Caused by: java.lang.ExceptionInInitializerError
        at com.here.android.mpa.internal.cl.<init>(PlacesBaseRequest.java:61)
        at com.here.android.mpa.internal.da.<init>(PlacesGeocodeRequest.java:32)
        at com.here.android.mpa.search.GeocodeRequest.<init>(GeocodeRequest.java:37)
```

**Comment by starand** [comment]
Hi @inglab-guster,

Which value did you get in onEngineInitializationCompleted(Error error) callback?
Can you reproduce the same issue using github sample https://github.com/heremaps/here-android-sdk-examples/tree/master/geocoder-and-reverse-geocoder ?

**Comment by inglab-guster** [comment]
Working now. Looks like the SDK required `ACCESS_WIFI_STAT` permission. I think this should be explicitly stated in the document.
