### ISSUE TITLE
Proper way to re-init mapEngine after failed

### ISSUE THREAD

**Issue by bluesnow4425** [heremaps/here-android-sdk-examples#281]
hi we found out that in certain brands devices, map engine gets failed to initialize easily after kill the app process and re-launch. I tried to re-init the mapEngine when i got init Error, but it seems that the map engine gets failed forever if it gets it once.
Is there any better way to re-init map engine while it init fails?

**Comment by starand** [comment]
Hi @bluesnow4425 
Can you share device names?
We never bumped in that issue. What yo can try, to delete SDK cache (try to remove /sdcard/.here-maps folder).
Also you can try to use MapSettings.setIsolatedDiskCacheRootPath() which allows to change SDK cache path.

**Comment by bluesnow4425** [comment]
Mostly if we use google phone, it happens more frequently. If we force to kill the app process, there's about 10-20% to crash. I use MapSettings.setIsolatedDiskCacheRootPath() in Application class which executes as soon as app launches.

**Comment by starand** [comment]
What was the error code?

**Comment by starand** [comment]
@bluesnow4425 is there any updates?

**Comment by bluesnow4425** [comment]
i remember it's an unknown error. I'll post the log in a day or two.

**Comment by starand** [comment]
@bluesnow4425 please add more details like **error.getDetails()** and **error.getStackTrace()**. Thank you!

**Comment by bluesnow4425** [comment]
java.lang.RuntimeException: Cannot initialize the engine twice
        at com.nokia.maps.MapsEngine.<init>(MapsEngine.java:21)
        at com.nokia.maps.MapsEngine.c(MapsEngine.java:9)
        at com.nokia.maps.MapsEngine.a(MapsEngine.java:36)
        at com.nokia.maps.MapsEngine.a(MapsEngine.java:24)
        at com.here.android.mpa.common.MapEngine.init(MapEngine.java:1)

**Comment by starand** [comment]
Most likely you are trying to init MapEngine/MapFragment in different threads. Try to synchronize this.

**Comment by bluesnow4425** [comment]
`Unknown error occurred during engine init` i think this is details.
and I'm getting 
```
java.lang.RuntimeException: Cannot initialize the engine twice
        at com.nokia.maps.MapsEngine.<init>(MapsEngine.java:21)
        at com.nokia.maps.MapsEngine.c(MapsEngine.java:9)
        at com.nokia.maps.MapsEngine.a(MapsEngine.java:36)
        at com.nokia.maps.MapsEngine.a(MapsEngine.java:24)
        at com.here.android.mpa.common.MapEngine.init(MapEngine.java:1)
```
as stacktrace.

It says that the engine can't initialize twice, but first time fails and MapEngine.isInitialized() returns false either. Tried several ways but the only one works is to exit the app process and relaunchs again.

**Comment by starand** [comment]
Ok, we never observed this issue, but from sources, it looks like initialization is done in at least two parallel threads. Other customers also do not report the issue. So it is difficult to reproduce.
Can you remove business logic from your app and share with us? Or can you add minimal changes to the github sample in order to reproduce?
Please share devices models as well.

**Comment by bluesnow4425** [comment]
https://github.com/bluesnow4425/here_map_init_research here's the repo. Tried and crash reproduce-able. I'm using google pixel 2 with latest android version.

**Comment by starand** [comment]
Ok, I did not manage to get to the end of registration process =), but I saw few mapEngine/Fragment init() calls. That cause synchronization issue. As we are near the end of SDK 3.13 release, the fix can be included only in 3.14 release. As a workaround, synchronize all calls of MapEngine (Fragment calls MapEngine init method internally). For your case you can init Map on the application start (once), and the next calls (even simultaneous) should run w/o problems. Or add some pause before calling init() method second time.
We will continue investigation a bit later.

**Comment by Merlin1stHere** [comment]
@bluesnow4425 What is the first error you got before running mapEngine init again? Please provide error code and details string (Error.getDetails).

**Comment by starand** [comment]
@bluesnow4425 is there any updates? Could you please provide requested info? Or did you solve the issue?

**Comment by bluesnow4425** [comment]
Ｗe still facing init error sometimes, especially after the app crashes. We do **Runtime.getRuntime().exit(0)** to kill the whole process and relaunch the app again.

**Comment by starand** [comment]
But was you able to get the init error? "What is the first error you got before running mapEngine init again?"

**Comment by bluesnow4425** [comment]
I think it's the same with [my post](https://github.com/heremaps/here-android-sdk-examples/issues/281#issuecomment-532597412) above.

**Comment by victorgutsu** [comment]
Does somebody resolved that issue? im still able to reproduce same error as above 
https://github.com/heremaps/here-android-sdk-examples/issues/384
