### ISSUE TITLE
Crash when opening turn-by-turn navigation 

### ISSUE THREAD

**Issue by strongmayer** [heremaps/here-android-sdk-examples#332]
I tried the turn-by-turn navigation example with my key, token, license and it worked fine, at least the map appeared and I could see the rotue on the map.

I integrated it as a module inside my app and I received the following crash when opened map screen. Please note that I use the same code as the example app. The crash occures every time I want to open the navigation activity. The navigation activity is not the launcher activity of my app, but I open it inside from a menu. I also made a test: if I set it as launcher activity, then it works fine.

Can anything from my app disturb the navigation activity/its background network operations? Can anybody help me with that?

Process: com.route4me.routeoptimizer, PID: 20269
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at ac.<init>(Unknown Source:21)
        at y.getErrorStream(Unknown Source:48)
        at com.here.network.NetworkProtocol$GetTask.cleanup(NetworkProtocol.java:18)
        at com.here.network.NetworkProtocol$GetTask.doInBackground(NetworkProtocol.java:355)
        at com.here.network.NetworkProtocol$GetTask.doInBackground(NetworkProtocol.java:1)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by strongmayer** [comment]
I found the problem. It was caused by CloudFlare. As I disabled it, here.com navigation started to work.
