### ISSUE TITLE
Map Initialization error in Navigation 

### ISSUE THREAD

**Issue by shruti-techindustan** [heremaps/here-android-sdk-examples#347]
Attempt to read from field 'java.util.concurrent.Semaphore com.nokia.maps.e0.a' on a null object reference
        at com.nokia.maps.e0.b(BaseTextureView.java:1)
        at com.nokia.maps.e0$d.a(BaseTextureView.java:8)
        at com.nokia.maps.e0$b.onSurfaceTextureSizeChanged(BaseTextureView.java:3)

**Comment by starand** [comment]
@shruti-techindustan which SDK version do you use?
Can you reproduce the same issue on any of our github sample?

**Comment by shruti-techindustan** [comment]
@starand 
SDK Version : 3.13.3.105

**Comment by NazarKacharaba** [comment]
Hi @shruti-techindustan 
Were you able to reproduce this crash?
