### ISSUE TITLE
Carash on BaseTextureView.java line 1 com.nokia.maps.e0.b

### ISSUE THREAD

**Issue by binod-techindustan** [heremaps/here-android-sdk-examples#374]
These doesn't occur all the time but sometime I got crash report of this in Firebase. Here is what we got from the log.
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.util.concurrent.Semaphore com.nokia.maps.e0.a' on a null object reference
       at com.nokia.maps.e0.b(BaseTextureView.java:1)
       at com.nokia.maps.e0$d.a(BaseTextureView.java:8)
       at com.nokia.maps.e0$b.onSurfaceTextureSizeChanged(BaseTextureView.java:3)
       at android.view.TextureView.onSizeChanged(TextureView.java:367)
       at android.view.View.sizeChange(View.java:19861)
       at android.view.View.setFrame(View.java:19822)
       at android.view.View.layout(View.java:19725)
       at com.here.android.mpa.mapping.MapView.onLayout(MapView.java:6)
       at android.view.View.layout(View.java:19728)
       at android.view.ViewGroup.layout(ViewGroup.java:6149)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1084)
       at android.view.View.layout(View.java:19728)
       at android.view.ViewGroup.layout(ViewGroup.java:6149)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19728)
       at android.view.ViewGroup.layout(ViewGroup.java:6149)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19728)
       at android.view.ViewGroup.layout(ViewGroup.java:6149)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:19728)
       at android.view.ViewGroup.layout(ViewGroup.java:6149)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
       at android.view.View.layout(View.java:19728)
       at android.view.ViewGroup.layout(ViewGroup.java:6149)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:819)
       at android.view.View.layout(View.java:19728)
       at android.view.ViewGroup.layout(ViewGroup.java:6149)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2615)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2324)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1469)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7315)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:988)
       at android.view.Choreographer.doCallbacks(Choreographer.java:800)
       at android.view.Choreographer.doFrame(Choreographer.java:735)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:974)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:175)
       at android.app.ActivityThread.main(ActivityThread.java:6724)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

```

**Comment by NazarKacharaba** [comment]
What version of the SDK crashed?

**Comment by NazarKacharaba** [comment]
It will be fixed in 3.16 release(1 July).
