### ISSUE TITLE
MapEngine init twice!

### ISSUE THREAD

**Issue by victorgutsu** [heremaps/here-android-sdk-examples#384]

**Comment by NazarKacharaba** [comment]
Hi @victorgutsu 
What version of the SDK do you use? Could you also  provide `error.getStackTrace()`?

**Comment by victorgutsu** [comment]
im using the last 3.16 premium sdk

here the stacktrace:


```
2020-07-17 17:08:46.555 18018-18018/com.here.android.tutorial E/error: java.lang.RuntimeException: Cannot initialize the engine twice
        at com.nokia.maps.MapsEngine.<init>(MapsEngine.java:2601)
        at com.nokia.maps.MapsEngine.g(MapsEngine.java:7)
        at com.nokia.maps.MapsEngine.a(MapsEngine.java:65)
        at com.nokia.maps.MapsEngine.a(MapsEngine.java:34)
        at com.here.android.mpa.common.MapEngine.init(MapEngine.java:1)
        at com.nokia.maps.b2.a(MapFragmentImpl.java:21)
        at com.here.android.mpa.mapping.AndroidXMapFragment.init(AndroidXMapFragment.java:2)
        at com.here.android.tutorial.MapFragmentView$6.onEngineInitializationCompleted(MapFragmentView.java:111)
        at com.here.android.mpa.common.MapEngine.init(MapEngine.java:12)
        at com.here.android.tutorial.MapFragmentView.initMapFragment(MapFragmentView.java:108)
        at com.here.android.tutorial.MapFragmentView.<init>(MapFragmentView.java:58)
        at com.here.android.tutorial.MainActivity.setupMapFragmentView(MainActivity.java:97)
        at com.here.android.tutorial.MainActivity.onRequestPermissionsResult(MainActivity.java:86)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8474)
        at android.app.Activity.dispatchActivityResult(Activity.java:8296)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5136)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5184)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7857)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```
