### ISSUE TITLE
No implementation found for boolean com.nokia.maps.MapsEngine.setAppCredentials_native

### ISSUE THREAD

**Issue by GhRyuJin** [heremaps/here-android-sdk-examples#70]
FATAL EXCEPTION: main
                                                                    Process: com.internation.ligo, PID: 7105
                                                                    java.lang.UnsatisfiedLinkError: No implementation found for boolean com.nokia.maps.MapsEngine.setAppCredentials_native(java.lang.String, java.lang.String, java.lang.String, java.lang.String, int) (tried Java_com_nokia_maps_MapsEngine_setAppCredentials_1native and Java_com_nokia_maps_MapsEngine_setAppCredentials_1native__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2I)
                                                                        at com.nokia.maps.MapsEngine.setAppCredentials_native(Native Method)
                                                                        at com.nokia.maps.MapsEngine.e(MapsEngine.java:688)
                                                                        at com.nokia.maps.MapsEngine.a(MapsEngine.java:476)
                                                                        at com.nokia.maps.MapsEngine.a(MapsEngine.java:364)
                                                                        at com.here.android.mpa.common.MapEngine.init(MapEngine.java:260)
                                                                        at com.nokia.maps.bw.a(MapFragmentImpl.java:131)
                                                                        at com.here.android.mpa.mapping.MapFragment.init(MapFragment.java:112)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511)
                                                                        at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:150)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5621)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
                                                                    	Suppressed: java.lang.Throwable: HERE SDK Version: 3.5.0.466
                                                                        at com.nokia.maps.MapsEngine$l.uncaughtException(MapsEngine.java:378)
                                                                        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

**Comment by starand** [comment]
Hi GhRyuJin,
Which SDK version do you use? Which phone? ABI? Other significant details?
The error actually means your HERE-sdk.aar is corrupted. Try to copy it again in your project folder.
If you still can reproduce the issue, please provide requested details.
